In [ ]:

n=int(input())
sum=0
for i in range(n):
   sum=sum+i
print(sum)

5
12


In [ ]:
a=input()
b=len(a)
for i in range(b):
   print(a[0])

query
q
q
q
q
q


In [ ]:
a=3
product=1
for i in range(1,a+1):
    m=int(input())
    product=product*m
print(product)

2
3
7
42


In [ ]:
n=int(input())
m=int(input())
total=0
for i in range(n,m):
    if(i%2==0):
     total=total+1
print(total)

1
11
5


In [ ]:
n=int(input())
m=int(input())
even=0
odd=0
for i in range(n,m):
    if(i%2==0):
     even=even+1
    else:
        odd=odd+1
print("total even numbers is :",even)
print("total odd numbers is :", odd)


1
11
total even numbers is : 5
total odd numbers is : 5


In [ ]:
n=4

for i in range(n+1):
   print(i*" * ")




 * 
 *  * 
 *  *  * 
 *  *  *  * 


In [ ]:
n=4
for i in range(n):
    print(n*" * ")

 *  *  *  * 
 *  *  *  * 
 *  *  *  * 
 *  *  *  * 


In [ ]:
n=4
for i in range(n):
    print(n* str(i))


0000
1111
2222
3333


In [ ]:
n=4
for i in range(1,n+1):
  if(i==n):
       print(i*" + ")
  if(i!=n):
     print(i*" * ")


 * 
 *  * 
 *  *  * 
 +  +  +  + 


In [ ]:
a="5"
b="4"
print(a+b)

54


In [ ]:
a="5"
b=4
print(a*b)

5555


In [ ]:
n=4
for i in range(1,n+1):
  print(str(i)*i)
for i in range(1,n+1):
  print(str(i)*i)

1
22
333
4444
1
22
333
4444


In [ ]:
a="5"
b="4"
c=a+b

In [ ]:
m=int(input())
n=int(input())
for i in range(1,m+1):
    print(str(i)*n)

2
3
111
222


In [ ]:
m=int(input())
n=int(input())
for i in range(10,m+n):
     print((str(i)+" ")*n)

10
5
10 10 10 10 10 
11 11 11 11 11 
12 12 12 12 12 
13 13 13 13 13 
14 14 14 14 14 


In [ ]:
n=int(input())
for i in range(0,n):
    print(i)

10
0
1
2
3
4
5
6
7
8
9


In [ ]:
n=int(input())
sum=0
for i in range(n):
    m=int(input())
    sum=sum+m
print(sum/n)


4
3
4
6
7
5.0


In [ ]:
n=4
for i in range(1,n+1):
  print(i*" * ")
for i in range(1,n+1):
  print(i*" * ")

 * 
 *  * 
 *  *  * 
 *  *  *  * 
 * 
 *  * 
 *  *  * 
 *  *  *  * 


In [ ]:
m=int(input())
n=int(input())
product=1
for i in range(m,n+1):
    product=product*i
print(product)


5
7
210


In [ ]:
a=int(input())
b=int(input())
product=1
for num in range(a,b):
     product=product*num
print(product)

5
10
15120


In [ ]:
a=int(input())
c_s=str(a)
sum=0
for i in range(len(c_s)):
     sum=sum+int(c_s[i])
print(sum)


15467
23


In [ ]:
a=int(input())
c_s=str(a)
sum=0
for i in range(len(c_s)):
    sum=sum+int(c_s[i])
print(sum)


151893
27


In [ ]:
a=5
for i in range(a,0,-1):
    print(i)

5
4
3
2
1


In [ ]:
n=int(input())
product=1
for i in range(n,0,-1):
    product=product*i
print(product)

7
5040


In [ ]:
a="tahesim"
for char in a:
    print(char)

t
a
h
e
s
i
m


In [ ]:
a="tahesim"
b=" "
for char in a:
    b=char+b
print(b)

misehat 


In [ ]:
a=151893
b=str(a)
sum=0
for char in b:
    sum=sum+int(char)
print(sum)

27


In [ ]:
a=(input())
print(a[::-1])


tash
hsat


In [ ]:
number=input()
m_num=0
for num in number:
    convert_int=int(num)
    if(convert_int>m_num):
        m_num=int(num)
print(m_num)


13423
4


In [ ]:
secret_message="-R-a-v-i-"
print(secret_message[1:8:2])

Ravi


In [ ]:
a="Waterfall"
part=a[1:6:3]
print(part)

ar


In [ ]:
mobile=" 987 65 43210 "
mobile=mobile.strip()
print(mobile)

987 65 43210


In [ ]:
name="ravi."
name=name.strip(".")
print(name)


ravi


In [ ]:
name="vasu@vasu@"
name=name.strip("@")
print(name)

vasu@vasu


In [ ]:
name=", .. ,, ravi ,, .. ,"
name=name.strip(" ,. ")
print(name)

ravi


In [ ]:
sentence="teh cat and teh dog"
sentence=sentence.replace("teh","shirin's")
print(sentence)

shirin's cat and shirin's dog


In [ ]:
url="https://ontegomodel.com"
is_secure_url=url.startswith("https:")
print(is_secure_url)

True


In [ ]:
gmail_id="rahul123@gmail.com"
is_gmail=gmail_id.endswith("@gmail.com")
print(is_gmail)

True


In [ ]:
name="ravi"
print(name.upper())

RAVI


In [ ]:
name="RaVi"
print(name.lower())

ravi


In [ ]:
a="KLE BCA"
index=a.index("BCA")
print(index)

4


In [ ]:
a="KLE BCA ENG"
count_E=a.count("E")
print(count_E)

2


In [ ]:
text="coo coo"
word_index=text.index("ha")
print(word_index)

ValueError: substring not found

In [ ]:
is_lower="hello ravi!".islower()
print(is_lower)


True


In [ ]:
is_upper="HELLO RAVI!".isupper()
print(is_upper)


True


In [ ]:
a="apple mango"
b=a.capitalize()
print(b)

Apple mango


In [ ]:
s="07-11-2020"
t=s.replace("-","/")
print(t)

07/11/2020


In [ ]:
a="Madam"
b=a.lower()
c=""
for char in b:
    c=char+c
if b==c:
    print("palindrome")
else:
    print("not palindrome")
print(c)
print(b)

palindrome
madam
madam


In [ ]:
for i in range(2):
    print("outer:"+str(i))
    for j in range(2):

        print("inner:"+str(j))

outer:0
inner:0
inner:1
outer:1
inner:0
inner:1


In [ ]:
for num in range(2):
   print("loop iteration number:"+str(num))
   a=0
   while(a<3):
      print("inner number :"+str(a))
      a=a+1

loop iteration number:0
inner number :0
inner number :1
inner number :2
loop iteration number:1
inner number :0
inner number :1
inner number :2


In [ ]:
for i in range(5):
   if i==3:
      break
   print(i)
print("End")

0
1
2
End


In [ ]:
for i in range(4):
   print("iteration number : "+str(i))
   if i==3:
      break
   print(i)
print("program ended")

iteration number : 0
0
iteration number : 1
1
iteration number : 2
2
iteration number : 3
program ended


In [ ]:
for i in range(4):
   print("iteration number : "+str(i))
   if i==2:
      continue
   print(i)
print("program ended")

iteration number : 0
0
iteration number : 1
1
iteration number : 2
iteration number : 3
3
program ended


In [ ]:
for i in range(4):
   if i==2:
     pass
   else:
     print(i)

0
1
3


In [ ]:
a=input()
for char in a:
  print(ord(char))


Darshan
68
97
114
115
104
97
110


In [ ]:
a=input()
for char in a:
  print(char)

Darshan
D
a
r
s
h
a
n


In [ ]:
a=input()
sum=0
for num in a:

   sum=sum+ord(num)
print(sum)

Tahesim
715


In [ ]:
S=input()
N=int(input())
sum=0

for char in S:
    value=ord(char)
    if value==N:
        sum=sum+1
print(sum)




TAHESIM
65
1


In [ ]:
a=2
list_a=[5, "six",a, 8.2]
print(type(list_a))
print(list_a)

<class 'list'>
[5, 'six', 2, 8.2]


In [ ]:
a=2
list_a=[5,"six",a,8.2]
list_b=[1,list_a]
print(list_b)

[1, [5, 'six', 2, 8.2]]


In [ ]:
a=2
list_a=[5,"six",a,8.2]
print(len(list_a))lis

4


In [ ]:
a=2
list_a=[5,"six",a,8.2]
print(list_a[1])

six


In [ ]:
a=2
list_a=[5,"six",a,8.2]
for item in list_a:
    print(item)

5
six
2
8.2


In [ ]:
list_a=[1,2,3]
list_b=["a","b","c"]
list_c=list_a + list_b
print(list_c)

[1, 2, 3, 'a', 'b', 'c']


In [ ]:
list_a=[]
print(list_a)
for i in range(1,4):
     list_a += [i]
print(list_a)

[]
[1, 2, 3]


In [ ]:
list_a=[1,2]
list_b=list_a * 3
print(list_b)

[1, 2, 1, 2, 1, 2]


In [ ]:
list_a=[5,"six",2,8.2]
list_b=list_a[: 2]
print(list_b)

[5, 'six']


In [ ]:
list_a=["R", "B","G","O","W"]
list_b=list_a[0:5:3]
print(list_b)

['R', 'O']


In [ ]:
color="Red"
list_a=list(color)
print(list_a)

['R', 'e', 'd']


In [ ]:
list_a=list(range(4))
print(list_a)

[0, 1, 2, 3]


In [ ]:
list_a=[1,2,3,5]
print(list_a)
list_a[3]=4
print(list_a)

[1, 2, 3, 5]
[1, 2, 3, 4]


In [ ]:
message="sea you soon"
message[2]="e"
print(message)

TypeError: 'str' object does not support item assignment

In [ ]:
list_a=[10,20,30,40]
list_b=[]
for i in list_a:
   c=i*2
   list_b=list_b+[c]
print(list_b)

[20, 40, 60, 80]


In [ ]:
num="1 2 3 4"
num_list=num.split()
print(num_list)

['1', '2', '3', '4']


In [ ]:
num="1.2.3.4"
num_list=num.split(".")
print(num_list)



['1', '2', '3', '4']


In [ ]:
m=list(input().split())
print(m)

10 20 30 six 15.0
['10', '20', '30', 'six', '15.0']


In [ ]:
m=list(input())
print(m)

10 20 30
['1', '0', ' ', '2', '0', ' ', '3', '0']


In [ ]:
string_a="python is a programming language"
list_a=string_a.split('a')
print(list_a)

['python is ', ' progr', 'mming l', 'ngu', 'ge']


In [ ]:
list_a=['python is ', ' progr', 'mming l', 'ngu', 'ge']
string_a="a".join(list_a)
print(string_a)

python is a programming language


In [ ]:
def greet():
    print("hello")
name=input()
print(name)
greet()

tash
tash
hello


In [ ]:
def fun_name():
   print("function calling")
fun_name()

function calling


In [ ]:
name=input()
demo()
print(name)

def demo():
    print("hello")

tahesim


NameError: name 'demo' is not defined

In [ ]:
def greet(word):
    msg="Hello " + word
    print(msg)

name=input()
greet(word=name)

tahesim
Hello tahesim


In [ ]:
def greet(name,age):
    msg="Hello " + name+" my age "+str(age)
    print(msg)

name=input()
age=int(input())
greet(name,age)

tahesim
18
Hello tahesim my age 18


In [ ]:
def greet(a,b):
    print(a + " " +str(b))


name=input()
age=int(input())
greet(name,age)

tahesim
18
tahesim 18


In [ ]:
def add(a):
   if(a%2==0):
      print("even")
   else:
      print("odd")
a=int(input())
add(a)

10
even


In [ ]:
def printdetails(id,name="vasu",age="35"):
    print("id is", id)
    print("name is",name)
    print("age is",age)
printdetails(101)

id is 101
name is vasu
age is 35


In [ ]:
a=2
tuple_a=(5,"six",a,8.2)
print(type(tuple_a))
print(tuple_a)


<class 'tuple'>
(5, 'six', 2, 8.2)


In [ ]:
a=2
tuple_a=(5,"six",a,8.2)
print(tuple_a[1])

six


In [ ]:
tuple_a=(1,2,3,4,5)
tuple_a[3]=4
print(tuple_a)

TypeError: 'tuple' object does not support item assignment

In [ ]:
tuple_a=tuple(range(4))
print(tuple_a)

(0, 1, 2, 3)


In [ ]:
color="Red"
tuple_a=tuple(color)
print(tuple_a)

('R', 'e', 'd')


In [ ]:
tuple_a=(1,2,3,4)
is_part=5 in tuple_a
print(is_part)

False


In [ ]:
tuple_a=(1,2,3,4)
is_part=1 not in tuple_a
print(is_part)

False


In [ ]:
word='python'
is_part='th' in word
print(is_part)

True


In [ ]:
list_a=[1,2,3]
tuple_a=tuple(list_a)
print(tuple_a)

(1, 2, 3)


In [ ]:
pet=True
aggresive=False
if pet and not aggresive:

    print("pet is not aggresive")
else:
    print("pet is aggresive")

pet is not aggresive


In [ ]:
a={1,2,3,4,}
a.add(7)
print(a)

{1, 2, 3, 4, 7}


In [ ]:
a={10,20,30,40}
a.update([11,12])
print(a)

{40, 10, 11, 12, 20, 30}


In [ ]:
a={11,12,13,14}
a.remove(12)
print(a)

{11, 13, 14}


In [ ]:
a={11,12,13,14}
a.discard(12)
print(a)

{11, 13, 14}


In [ ]:
a={11,12,13,14}
a.pop()
print(a)

{12, 13, 14}


In [ ]:
a={11,12,13,14}
a.clear()
print(a)

set()


In [ ]:
a={11,12,13,14}
b={10,20,30}
c=a.union(b)
print(c)

{20, 30, 10, 11, 12, 13, 14}


In [ ]:
a={1,2,3,4}
b={3,4,5,6}

print("intersection:",a.intersection(b))

intersection: {3, 4}


In [ ]:
a={1,2,3,4}
b={3,4,5,6}
print("difference(a-b):",a.difference(b))


difference(a-b): {1, 2}


In [ ]:
a={1,2,3,4}
b={3,4,5,6}
print("issubset:",{1,2}.issubset(a))

issubset: True


In [ ]:
a={1,2,3,4}
b={3,4,5,6}
print("issuperset:",a.issuperset({1,2}))

issuperset: True


In [ ]:
student={"name":"vasu","age": 24, "course":"python"}
print(student["name"])

vasu


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
print("original dictionary:", student)

original dictionary: {'name': 'vasu', 'age': 22, 'course': 'python'}


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
print("get('age'):",student.get("age"))
print("get('grade','not found'):",student.get("grade","not found"))

get('age'): 22
get('grade','not found'): not found


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
print("keys()", student.keys())

keys() dict_keys(['name', 'age', 'course'])


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
print("values()", student.values())

values() dict_values(['vasu', 22, 'python'])


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
print("items():",student.items())

items(): dict_items([('name', 'vasu'), ('age', 22), ('course', 'python')])


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
student.update({"age": 23, "grade":"A"})
print("after update:", student)

after update: {'name': 'vasu', 'age': 23, 'course': 'python', 'grade': 'A'}


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
removed=student.pop("course")
print("after pop('course):",student,"(removed:",removed,")")

after pop('course): {'name': 'vasu', 'age': 22} (removed: python )


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
last_removed=student.popitem()
print("after popitem():",student,"(removed:",last_removed,")")

after popitem(): {'name': 'vasu', 'age': 22} (removed: ('course', 'python') )


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
temp=student.copy()
temp.clear()
print("after clear():",temp)

after clear(): {}


In [ ]:
student={"name":"vasu","age":22,"course":"python"}
keys=["a","b","c"]
new_dict=dict.fromkeys(keys,0)
print("fromkeys(['a','b','c'],0):",new_dict)

fromkeys(['a','b','c'],0): {'a': 0, 'b': 0, 'c': 0}


In [ ]:
student={"name":"vasu","age":23}
print("Before sedefault:",student)
print("setdefault('grade','A')",student.setdefault("grade","A"))
print("after setdefault:",student)

Before sedefault: {'name': 'vasu', 'age': 23}
setdefault('grade','A') A
after setdefault: {'name': 'vasu', 'age': 23, 'grade': 'A'}


In [ ]:
class student:
   def __init__(self):
       self.name="vasu"
       self.my_age=24
   def display(self):
       print("name:",self.name, "Age:", self.my_age)
s1=student()
s2=student()

s1.display()
s2.display()

name: vasu Age: 24
name: vasu Age: 24


In [ ]:
class Bank:
    def __init__(self,balance):
       self.balance=balance

    def deposite(self,amount):
        self.balance+=amount

    def get_balance(self):
       return self.balance

acc=Bank(1000)
acc.deposit(500)
print("balance:",acc.get_balance())

AttributeError: 'Bank' object has no attribute 'deposit'

In [ ]:
class Animal:
     def sound(self):
         print("Animals make sounds")

class Dog(Animal):
     def sound(self):
         super().sound()
         print("Dog barks")
d=Dog()
d.sound()



Animals make sounds
Dog barks


In [ ]:
class calculator:
     def add(self,a,b):
         print("parents class: Adding numbers")
         return a+b
class AdvancedCalculator(calculator):
    def add(self,a,b):
        result=super().add(a,b)
        print("Child class: Adding 10 extra")
        return result+10
calc=AdvancedCalculator()
print("final Result:",calc.add(5,3))

parents class: Adding numbers
Child class: Adding 10 extra
final Result: 18


In [ ]:
class Dog:
   def sound(self):
       return "Bark"
class Cat:
    def sound(self):
        return"meow"
class cow:
    def sound(self):
        return"Moo"
animals=[Dog(),Cat(),cow()]


for animal in animals:
     print(animal.sound())


Bark
meow
Moo


In [ ]:
!pip install numpy
import numpy as np

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr2 = np.array([[1,2,3,],[4,5,6]])
print(arr2)
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(np.dot(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1])
print(arr[1:4])


20
[20 30 40]


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
arr[1]=99
print(arr)

[10 99 30 40 50]


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,0])
print(arr[1,2])

1
6


In [ ]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr[0,1,1])

4


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:2,1:])

[20 30 40]
[10 20 30]
[10 30 50]
[[2 3]
 [5 6]]


In [ ]:
arr=np.array([10,20,30,40,])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))



100
25.0
11.180339887498949
10
40


In [ ]:
a=np.random.rand(3,3)
print(a)

b=np.random.randint(1,100,(3,3))
print(b)

[[0.96293202 0.48841109 0.39398149]
 [0.08560924 0.18006463 0.88098832]
 [0.64980183 0.43567168 0.02010622]]
[[58 55 58]
 [40 14 72]
 [ 5 54 92]]


In [ ]:
a={"name":"tahesim","age":17}

print(a)

{'name': 'tahesim', 'age': 17}


In [ ]:
a={"name":"tahesim","age":17}
print(a["name"])

tahesim


In [ ]:
a={"name":"tahesim","age":17}
a["course"]="python"
print(a)

{'name': 'tahesim', 'age': 17, 'course': 'python'}


In [ ]:
a={"name":"tahesim","age":17}
del a["age"]
print(a)

{'name': 'tahesim'}


In [ ]:
Book={}
def add(name,grade):
  Book[name]=grade
add("tahesim",350)
print(Book)


{'tahesim': 350}


In [ ]:
Book={}
def add(name,grade):
  Book[name]=grade
def update(name,grade):
  Book[name]=grade
add("tahesim",350)
update("tahesim",500)
print(Book)


{'tahesim': 500}


In [ ]:
Book={"student1":30,"student2":100,"student3":00,"Ajit":850,"student5":100,"student6":1600}
def add(name,grade):
  Book[name]=grade
  print("successfully added")
def update(name,grade):
  Book[name]=grade
  print("successfully updated")
def delete(name):
  if name in Book:
    del Book [name]

  else:
    print(name+" not found in the Book")
    print("successfully deleted")
def display():
   if Book:
      for key,value in Book.items():
        print(key + ":"+str(value))
   else:
        print("Book is empty")
def find_grades():
     first_class=[]
     second_class=[]
     third_class=[]
     failed=[]

     for name,marks in Book.items():
         if marks>=60:
           first_class.appened(name)
         elif marks>=50:
          second_class.appened(name)
         elif marks>=35:
           third_class.appened(name)
         else:
          failed.append(name)
          print("First class students:",first_class)
          print("second class students:",second_class)
          print("third class students:",third_class)
          print("failed studentds:",failed)
          print("\nSummary:")
          print("First class :",len(first_class))
          print("second class :",len(second_class))
          print("third class :",len(third_class))
          print("failed :",len(failed))

def main():
        print("\n student Grades Management system")
        print("1.add Book")
        print("2.update Book")
        print("3.delete")
        print("4.View book")
        print("5.exit")
        while True:
          n=int(input("enter the option"))
          if(n==1):
            name=input()
            grade=int(input())
            add(name,grade)
          elif(n==2):
            name=input()
            grade=int(input())
            add(name,grade)
          elif(n==3):
            name=input()
            grade=int(input())
            add(name,grade)
          elif(n==4):
            display_all_Book()


          elif(n==5):
              print("closing the program")
              break

          else:
             print("Invalid choice")
main()







 student Grades Management system
1.add Book
2.update Book
3.delete
4.View book
5.exit
enter the option3
tahesim
100
successfully added
enter the option5
closing the program


In [ ]:
a={10,20}
if a:
   print("not empty")
else:
      print("empty")

not empty


In [ ]:
s_n={"name":"vasu","age":19}
print(s_n.keys())

dict_keys(['name', 'age'])


In [ ]:
s_n={"name":"vasu","age":19}
print(s_n.values())

dict_values(['vasu', 19])


In [ ]:
s_n={"name":"vasu","age":19}
print(s_n.items())

dict_items([('name', 'vasu'), ('age', 19)])


In [ ]:
s_n={"name":"vasu","age":19}
for key,value in s_n.items():
  print(key +":"+str(value))

name:vasu
age:19
